# Generated by Django 4.2 on 2023-04-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
